[package]
name = "dep-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bonbon = { git = "https://github.com/lwus/bonbon.git", rev = "e0dbcdb2c717af0fbd610893b15b1d7e27e0aed1" }
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
mpl-token-metadata = "1.3.3"
solana-client = { git = "https://github.com/omertxyz/solana.git", rev = "35d6ef701ed8929ddb6d52e7946774c63c709e25" }
solana-program = { git = "https://github.com/omertxyz/solana.git", rev = "35d6ef701ed8929ddb6d52e7946774c63c709e25" }
solana-sdk = { git = "https://github.com/omertxyz/solana.git", rev = "35d6ef701ed8929ddb6d52e7946774c63c709e25" }
solana-transaction-status = { git = "https://github.com/omertxyz/solana.git", rev = "35d6ef701ed8929ddb6d52e7946774c63c709e25" }
spl-token-2022= "0.4.1"
solana-storage-bigtable = { git = "https://github.com/omertxyz/solana.git", rev = "35d6ef701ed8929ddb6d52e7946774c63c709e25" }
bundlr-sdk = {git = "https://github.com/kaustavha/rust-sdk", rev = "beab2a990edfb71eeeffa7f42e93ff121b08286e" }

[patch.crates-io]
aes-gcm-siv = { git = "https://github.com/lei2022/AEADs", rev = "d9d03399fbc1347a1c2941801c0743e847980757" }
curve25519-dalek = { git = "https://github.com/hariria/curve25519-dalek", rev = "1f39e7b369dc70f432370c9703229a45bfa9664e" }
